services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: dt-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dt_game
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dt-network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: dt-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dt-network

  # etcd 配置中心
  etcd:
    image: elcolio/etcd:latest
    container_name: dt-etcd
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/etcd-data
    healthcheck:
      test: ["CMD-SHELL", "etcdctl cluster-health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dt-network

  # RocketMQ NameServer
  rocketmq-namesrv:
    image: apache/rocketmq:5.1.4
    container_name: dt-rocketmq-namesrv
    ports:
      - "9876:9876"
    environment:
      - JAVA_OPT_EXT=-Xms512m -Xmx512m
    command: sh mqnamesrv
    volumes:
      - rocketmq_namesrv_logs:/home/rocketmq/logs
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/9876' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - dt-network

  # RocketMQ Broker
  rocketmq-broker:
    image: apache/rocketmq:5.1.4
    container_name: dt-rocketmq-broker
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
      - JAVA_OPT_EXT=-Xms512m -Xmx512m -Drocketmq.broker.diskSpaceWarningLevelRatio=0.98
    command: sh mqbroker -n rocketmq-namesrv:9876 autoCreateTopicEnable=true
    volumes:
      - rocketmq_broker_logs:/home/rocketmq/logs
      - rocketmq_broker_store:/home/rocketmq/store
    depends_on:
      rocketmq-namesrv:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/10911' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - dt-network

  # Dragon vs Tiger 应用服务
  dt-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dt-server
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - ETCD_CONFIG_KEY=/dt-server/config/dev
      - TZ=Asia/Shanghai
    ports:
      - "8087:8087"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      etcd:
        condition: service_healthy
      rocketmq-broker:
        condition: service_healthy
    networks:
      - dt-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
  etcd_data:
  rocketmq_namesrv_logs:
  rocketmq_broker_logs:
  rocketmq_broker_store:

networks:
  dt-network:
    driver: bridge

